/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectojuego;

import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.*;
//para el icono 
import java.awt.Image;
import java.awt.Toolkit;
/**
 *
 * @author BARRUETA
 */
public class acceso extends javax.swing.JFrame {
Connection conn=null;
PreparedStatement pst=null;
ResultSet rs=null;
    /**
     * Creates new form acceso
     */
    public acceso() {
        initComponents();
        this.setLocationRelativeTo(null);
      
      
    }
    
    //para el icono de la barra
    public Image getIconImage(){
        Image retValue=Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        salir = new javax.swing.JButton();
        usuario = new javax.swing.JLabel();
        contraseña = new javax.swing.JLabel();
        inuser = new javax.swing.JTextField();
        incontraseña = new javax.swing.JPasswordField();
        nuevo = new javax.swing.JButton();
        entrar = new javax.swing.JButton();
        im = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        salir.setBackground(new java.awt.Color(0, 0, 102));
        salir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        salir.setForeground(new java.awt.Color(255, 255, 255));
        salir.setText("EXIT");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        usuario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        usuario.setForeground(new java.awt.Color(255, 255, 255));
        usuario.setText("USER :");
        getContentPane().add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        contraseña.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        contraseña.setForeground(new java.awt.Color(255, 255, 255));
        contraseña.setText("PASSWORD :");
        getContentPane().add(contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));
        getContentPane().add(inuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 200, -1));

        incontraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incontraseñaActionPerformed(evt);
            }
        });
        getContentPane().add(incontraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 200, -1));

        nuevo.setBackground(new java.awt.Color(0, 0, 102));
        nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevousuario.png"))); // NOI18N
        nuevo.setText("jButton1");
        nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoActionPerformed(evt);
            }
        });
        getContentPane().add(nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 120, 120));

        entrar.setBackground(new java.awt.Color(0, 0, 102));
        entrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        entrar.setForeground(new java.awt.Color(255, 255, 255));
        entrar.setText("ENTER");
        entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarActionPerformed(evt);
            }
        });
        getContentPane().add(entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, -1, -1));

        im.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Person1.png"))); // NOI18N
        getContentPane().add(im, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pio.jpg"))); // NOI18N
        jLabel1.setAutoscrolls(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 341, 501));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
 System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_salirActionPerformed

    
    private void entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarActionPerformed
conn =MysqlConnect.ConnectDB();
String Sql= "Select * from tabusers where usuario=? and contraseña=?";
try{
    pst=conn.prepareStatement(Sql);
    pst.setString(1,inuser.getText());
    pst.setString(2,incontraseña.getText());
    rs=pst.executeQuery();
    if(rs.next()){
        JOptionPane.showMessageDialog(null,"bienvenido usuario");
        juego1 w=new juego1();//...............................................................welcome=juego1
        w.setVisible(true);
    }
    else{
        JOptionPane.showMessageDialog(null, "invalido usuario o pasword","acces denied",JOptionPane.ERROR_MESSAGE);
    } 
}catch(Exception e){
    JOptionPane.showMessageDialog(null, e);
}
        
this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_entrarActionPerformed

    private void nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoActionPerformed
        // TODO add your handling code here:
        nuevousuario formul = new  nuevousuario();
        formul.setVisible(true);
          this.dispose();// para cerrar la otra ventana 
    }//GEN-LAST:event_nuevoActionPerformed

    private void incontraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incontraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_incontraseñaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new acceso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contraseña;
    private javax.swing.JButton entrar;
    private javax.swing.JLabel im;
    private javax.swing.JPasswordField incontraseña;
    private javax.swing.JTextField inuser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton nuevo;
    private javax.swing.JButton salir;
    private javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables
}
