/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectojuego;
//para el icono 
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
/**
 *
 * @author BARRUETA
 */
public class pantalla extends javax.swing.JFrame {
//     private String nameCharacter            =       "";
//     
//    ImageIcon Imagen[]=new ImageIcon[12];

    /**
     * Creates new form memorama
     */
    public pantalla() {
        initComponents();
        this.setLocationRelativeTo(null);
        
//        for(int i =1;i<11;i++){
//            Imagen[i]= new ImageIcon (getClass().getResource("/imagenes2/"+ this.nameCharacter +".jpg"));
//        }
//        imagenal.setIcon(Imagen[1]);
//    }
//     //para el icono de la barra
//     public Image getIconImage(){
//        Image retValue=Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/icon.png"));
//        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        siguiente = new javax.swing.JButton();
        menu = new javax.swing.JButton();
        imagenal = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        textal = new javax.swing.JTextField();
        cargarimg = new javax.swing.JButton();
        columnas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        siguiente.setBackground(new java.awt.Color(0, 0, 153));
        siguiente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        siguiente.setForeground(new java.awt.Color(255, 255, 255));
        siguiente.setText("NEXT --->");
        siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteActionPerformed(evt);
            }
        });
        getContentPane().add(siguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 530, -1, -1));

        menu.setBackground(new java.awt.Color(0, 0, 255));
        menu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        menu.setForeground(new java.awt.Color(255, 255, 255));
        menu.setText("REGRESAR A MENU");
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });
        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, -1, -1));

        imagenal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        imagenal.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                imagenalAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(imagenal, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 220, 210));

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 260, 250));

        jPanel2.setBackground(new java.awt.Color(0, 255, 51));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 300, 280));
        getContentPane().add(textal, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 280, 40));

        cargarimg.setText("CARGAR IMAGEN");
        cargarimg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarimgActionPerformed(evt);
            }
        });
        getContentPane().add(cargarimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, -1, -1));

        columnas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/columnas.jpg"))); // NOI18N
        getContentPane().add(columnas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteActionPerformed
 memorama1 formul = new  memorama1();
        formul.setVisible(true);
        this.dispose();// para cerrar la otra ventana 
        // TODO add your handling code here:
    }//GEN-LAST:event_siguienteActionPerformed

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
juego1 formul = new  juego1();
        formul.setVisible(true);
        this.dispose();// para cerrar la otra ventana 
        // TODO add your handling code here:
    }//GEN-LAST:event_menuActionPerformed

    private void imagenalAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_imagenalAncestorAdded
      
        // TODO add your handling code here:
    }//GEN-LAST:event_imagenalAncestorAdded

    private void cargarimgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarimgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cargarimgActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(columnas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(columnas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(columnas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(columnas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new columnas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cargarimg;
    private javax.swing.JLabel columnas;
    private javax.swing.JLabel imagenal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton menu;
    private javax.swing.JButton siguiente;
    private javax.swing.JTextField textal;
    // End of variables declaration//GEN-END:variables
}
